name: help-center-scraper
services:
  - name: log-server
    source_dir: /log-server
    github:
      repo: HarryLee02/API-starter-pack
      branch: main
    run_command: python app.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: PORT
        value: "8080"

jobs:
  - name: daily-scraper
    source_dir: /
    github:
      repo: HarryLee02/API-starter-pack
      branch: main
    run_command: python main.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    schedule:
      cron: "0 2 * * *"  # Daily at 2 AM UTC
    envs:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: SUPPORT_URL
        value: ${SUPPORT_URL}
      - key: OPENAI_VECTOR_STORE_ID
        value: ${OPENAI_VECTOR_STORE_ID} 