services:
  scraper:
    build: .
    image: scraper:latest
    container_name: help-center-scraper
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPPORT_URL=${SUPPORT_URL}
      - OPENAI_VECTOR_STORE_ID=${OPENAI_VECTOR_STORE_ID}
    volumes:
      - scraper-logs:/app/logs
      - docs-volume:/app/docs

  log-server:
    build: ./log-server
    image: log-server:latest
    container_name: log-server
    ports:
      - "8080:8080"
    volumes:
      - scraper-logs:/app/logs
      - docs-volume:/app/docs
    restart: unless-stopped

volumes:
  scraper-logs:
    name: scraper-logs
  docs-volume:
    name: docs-volume